"""Fixed some issues related to task_id index

Revision ID: a30a08d84012
Revises: 4b73108b1abe
Create Date: 2026-02-15 19:01:37.377937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30a08d84012'
down_revision: Union[str, None] = '4b73108b1abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixz_celery_task_id', table_name='celery_task_executions')
    op.create_index('ixz_task_id', 'celery_task_executions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixz_task_id', table_name='celery_task_executions')
    op.create_index('ixz_celery_task_id', 'celery_task_executions', ['task_id'], unique=False)
    # ### end Alembic commands ###
